# -*- coding: utf-8 -*-
"""unet+densenet169.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5OK8fca35vmorJiJ7o5i4BdcYEUtrRH
"""

# ============================================
# CELL 1: MOUNT DRIVE + INSTALLS
# ============================================
from google.colab import drive
drive.mount('/content/drive')

!pip install -q segmentation-models-pytorch rasterio albumentations

# ============================================
# CELL 2: IMPORTS
# ============================================
import os
import zipfile
import random
import time

import numpy as np
import cv2
import rasterio
import matplotlib.pyplot as plt
import albumentations as A

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import segmentation_models_pytorch as smp
from skimage.morphology import skeletonize
from skimage.draw import line

# ============================================
# CELL 3: BASIC SETUP
# ============================================
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", DEVICE)

if DEVICE == "cuda":
    torch.backends.cudnn.benchmark = True

# ============================================
# CELL 4: UNZIP DATASET
# final_dataset.zip -> /content/final_dataset
# ============================================
ZIP_PATH = "/content/drive/MyDrive/final_dataset.zip"
EXTRACT_DIR = "/content/final_dataset"

os.makedirs(EXTRACT_DIR, exist_ok=True)

marker = os.path.join(EXTRACT_DIR, ".unzipped_done")
if not os.path.exists(marker):
    with zipfile.ZipFile(ZIP_PATH, "r") as zf:
        zf.extractall(EXTRACT_DIR)
    with open(marker, "w") as f:
        f.write("done")

print("✅ Dataset extracted to:", EXTRACT_DIR)

# ============================================
# CELL: MERGE TEST INTO VAL
# combines:
#   /content/final_dataset/val
#   /content/final_dataset/test
# into:
#   /content/final_dataset/val
# ============================================

import os
import shutil
from pathlib import Path

DATASET_ROOT = Path("/content/final_dataset/final_dataset/split")

VAL_IMG = DATASET_ROOT / "val" / "image"
VAL_MSK = DATASET_ROOT / "val" / "mask"

TEST_IMG = DATASET_ROOT / "test" / "image"
TEST_MSK = DATASET_ROOT / "test" / "mask"

def safe_mkdir(path):
    path.mkdir(parents=True, exist_ok=True)

def move_all_files(src_dir, dst_dir):
    safe_mkdir(dst_dir)

    moved = 0
    skipped = 0

    for file_path in sorted(src_dir.glob("*")):
        if not file_path.is_file():
            continue

        dst_path = dst_dir / file_path.name

        if dst_path.exists():
            print(f"Skipping existing file: {dst_path.name}")
            skipped += 1
            continue

        shutil.move(str(file_path), str(dst_path))
        moved += 1

    return moved, skipped

# checks
if not VAL_IMG.exists():
    raise FileNotFoundError(f"Missing folder: {VAL_IMG}")
if not VAL_MSK.exists():
    raise FileNotFoundError(f"Missing folder: {VAL_MSK}")
if not TEST_IMG.exists():
    raise FileNotFoundError(f"Missing folder: {TEST_IMG}")
if not TEST_MSK.exists():
    raise FileNotFoundError(f"Missing folder: {TEST_MSK}")

moved_img, skipped_img = move_all_files(TEST_IMG, VAL_IMG)
moved_msk, skipped_msk = move_all_files(TEST_MSK, VAL_MSK)

print("Moved test images -> val/image :", moved_img)
print("Skipped images                :", skipped_img)
print("Moved test masks  -> val/mask :", moved_msk)
print("Skipped masks                 :", skipped_msk)

# remove empty test folders
try:
    TEST_IMG.rmdir()
    TEST_MSK.rmdir()
    (DATASET_ROOT / "test").rmdir()
    print("Removed empty test folders")
except OSError:
    print("Test folders not removed automatically (may still contain files)")

# ============================================
# CELL: VERIFY FINAL COUNTS
# ============================================

def count_tifs(folder):
    return len([f for f in os.listdir(folder) if f.lower().endswith(".tif")])

TRAIN_IMG = DATASET_ROOT / "train" / "image"
TRAIN_MSK = DATASET_ROOT / "train" / "mask"

print("Train images:", count_tifs(TRAIN_IMG))
print("Train masks :", count_tifs(TRAIN_MSK))
print("Val images  :", count_tifs(VAL_IMG))
print("Val masks   :", count_tifs(VAL_MSK))
print("Test exists :", (DATASET_ROOT / "test").exists())

# ============================================
# CELL 5: FIND DATASET ROOT
# expects:
# train/image, train/mask, val/image, val/mask
# ============================================
def find_dataset_root(root):
    candidates = [root]
    for item in os.listdir(root):
        p = os.path.join(root, item)
        if os.path.isdir(p):
            candidates.append(p)

    for c in candidates:
        if (
            os.path.isdir(os.path.join(c, "train", "image")) and
            os.path.isdir(os.path.join(c, "train", "mask")) and
            os.path.isdir(os.path.join(c, "val", "image")) and
            os.path.isdir(os.path.join(c, "val", "mask"))
        ):
            return c

    raise FileNotFoundError(
        "Could not find dataset root containing train/image, train/mask, val/image, val/mask"
    )

BASE = str(DATASET_ROOT)

TRAIN_IMG = os.path.join(BASE, "train", "image")
TRAIN_MSK = os.path.join(BASE, "train", "mask")
VAL_IMG   = os.path.join(BASE, "val", "image")
VAL_MSK   = os.path.join(BASE, "val", "mask")

print("BASE     :", BASE)
print("TRAIN_IMG:", TRAIN_IMG)
print("TRAIN_MSK:", TRAIN_MSK)
print("VAL_IMG  :", VAL_IMG)
print("VAL_MSK  :", VAL_MSK)

# ============================================
# CELL 6: SANITY CHECK FILE COUNTS
# ============================================
def list_tifs(folder):
    return sorted([f for f in os.listdir(folder) if f.lower().endswith(".tif")])

train_images = list_tifs(TRAIN_IMG)
train_masks  = list_tifs(TRAIN_MSK)
val_images   = list_tifs(VAL_IMG)
val_masks    = list_tifs(VAL_MSK)

print("Train images:", len(train_images))
print("Train masks :", len(train_masks))
print("Val images  :", len(val_images))
print("Val masks   :", len(val_masks))

print("\nSample train image:", train_images[0] if len(train_images) else "None")
print("Sample train mask :", train_masks[0] if len(train_masks) else "None")
print("Sample val image  :", val_images[0] if len(val_images) else "None")
print("Sample val mask   :", val_masks[0] if len(val_masks) else "None")

# ============================================
# CELL 7: HELPERS (UPDATED NORMALIZATION)
# ============================================

def expected_mask_name_from_image(img_name):
    stem = img_name[:-4]
    parts = stem.split("_")

    if len(parts) != 3:
        raise ValueError(
            f"Unexpected image name format: {img_name}. Expected city_row_col.tif"
        )

    city, row, col = parts
    return f"{city}_mask_{row}_{col}.tif"


def compute_input_features(image_hwc):
    """
    Returns raw features (NO normalization here)

    Output:
    - 5 channels if NIR exists: [R, G, B, NDVI, NDWI]
    - 3 channels otherwise: [R, G, B]
    """
    image_hwc = image_hwc.astype(np.float32)
    c = image_hwc.shape[-1]

    rgb = image_hwc[:, :, :3].astype(np.float32)

    if c >= 4:
        r   = image_hwc[:, :, 0]
        g   = image_hwc[:, :, 1]
        b   = image_hwc[:, :, 2]
        nir = image_hwc[:, :, 3]

        eps = 1e-6
        ndvi = (nir - r) / (nir + r + eps)
        ndwi = (g - nir) / (g + nir + eps)

        feat = np.concatenate(
            [rgb, ndvi[..., None], ndwi[..., None]],
            axis=-1
        ).astype(np.float32)

        return feat, True

    return rgb.astype(np.float32), False

# ============================================
# NEW CELL: COMPUTE DATASET NORMALIZATION
# ============================================

def compute_dataset_stats(img_dir, max_samples=200):
    image_files = list_tifs(img_dir)
    image_files = image_files[:max_samples]  # speed-up (optional)

    channel_sum = None
    channel_sq_sum = None
    pixel_count = 0

    for img_name in image_files:
        img_path = os.path.join(img_dir, img_name)

        with rasterio.open(img_path) as src:
            image = src.read().transpose(1, 2, 0).astype(np.float32)

        feat, _ = compute_input_features(image)  # NO normalization

        h, w, c = feat.shape
        feat = feat.reshape(-1, c)

        if channel_sum is None:
            channel_sum = feat.sum(axis=0)
            channel_sq_sum = (feat ** 2).sum(axis=0)
        else:
            channel_sum += feat.sum(axis=0)
            channel_sq_sum += (feat ** 2).sum(axis=0)

        pixel_count += feat.shape[0]

    mean = channel_sum / pixel_count
    std = np.sqrt(channel_sq_sum / pixel_count - mean ** 2)

    std[std < 1e-6] = 1.0

    print("Dataset mean:", mean)
    print("Dataset std :", std)

    return mean.astype(np.float32), std.astype(np.float32)


# 👉 RUN THIS
DATA_MEAN, DATA_STD = compute_dataset_stats(TRAIN_IMG)

class RoadDataset(Dataset):
    def __init__(self, img_dir, mask_dir, mean, std, augment=False):
        self.img_dir = img_dir
        self.mask_dir = mask_dir
        self.images = list_tifs(img_dir)
        self.augment = augment

        self.mean = mean
        self.std = std

        if len(self.images) == 0:
            raise RuntimeError(f"No tif images found in {img_dir}")

        sample_img_path = os.path.join(self.img_dir, self.images[0])
        with rasterio.open(sample_img_path) as src:
            self.raw_band_count = src.count

        self.out_channels = 5 if self.raw_band_count >= 4 else 3

        if self.augment:
            self.transform = A.Compose([
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.5),
                A.RandomRotate90(p=0.5),
                A.Transpose(p=0.2),
                A.ShiftScaleRotate(
                    shift_limit=0.03,
                    scale_limit=0.05,
                    rotate_limit=10,
                    interpolation=cv2.INTER_LINEAR,
                    border_mode=cv2.BORDER_REFLECT_101,
                    p=0.4
                ),
                A.RandomBrightnessContrast(
                    brightness_limit=0.15,
                    contrast_limit=0.15,
                    p=0.3
                ),
                A.GaussNoise(
                    std_range=(0.01, 0.05),
                    mean_range=(0.0, 0.0),
                    p=0.2
                ),
            ])
        else:
            self.transform = None

        print(f"Dataset: {img_dir}")
        print(f"Channels: {self.out_channels}")
        print(f"Augment: {self.augment}")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        img_path = os.path.join(self.img_dir, img_name)

        mask_name = expected_mask_name_from_image(img_name)
        mask_path = os.path.join(self.mask_dir, mask_name)

        with rasterio.open(img_path) as src:
            image = src.read().transpose(1, 2, 0).astype(np.float32)

        with rasterio.open(mask_path) as src:
            mask = src.read(1).astype(np.float32)

        image, _ = compute_input_features(image)

        # ✅ APPLY DATASET NORMALIZATION HERE
        image = (image - self.mean) / self.std

        mask = (mask > 0).astype(np.float32)

        if self.transform is not None:
            augmented = self.transform(image=image, mask=mask)
            image = augmented["image"]
            mask = augmented["mask"]

        image = torch.from_numpy(image).permute(2, 0, 1).float()
        mask  = torch.from_numpy(mask).unsqueeze(0).float()

        return image, mask

# ============================================
# CELL 9: CREATE DATASETS + LOADERS
# ============================================
BATCH_SIZE = 16
NUM_WORKERS = 2

train_ds = RoadDataset(TRAIN_IMG, TRAIN_MSK, DATA_MEAN, DATA_STD, augment=True)
val_ds   = RoadDataset(VAL_IMG, VAL_MSK, DATA_MEAN, DATA_STD, augment=False)

assert train_ds.out_channels == val_ds.out_channels, \
    "Train and val have different channel setup"

IN_CHANNELS = train_ds.out_channels

train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=(NUM_WORKERS > 0),
    prefetch_factor=2 if NUM_WORKERS > 0 else None
)

val_loader = DataLoader(
    val_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    persistent_workers=(NUM_WORKERS > 0),
    prefetch_factor=2 if NUM_WORKERS > 0 else None
)

print("Train size      :", len(train_ds))
print("Val size        :", len(val_ds))
print("Input channels  :", IN_CHANNELS)
print("Batch size      :", BATCH_SIZE)
print("Num workers     :", NUM_WORKERS)

# ============================================
# CELL 10: MODEL
# Unet + DenseNet169 + Attention (scSE)
# ============================================

model = smp.Unet(
    encoder_name="densenet169",
    encoder_weights="imagenet",
    in_channels=IN_CHANNELS,
    classes=1,
    activation=None,
    decoder_attention_type="scse",
).to(DEVICE)

if DEVICE == "cuda":
    model = model.to(memory_format=torch.channels_last)

print("✅ Model ready")
print("Model type: Unet + DenseNet169 + scSE Attention")

# ============================================
# CELL 11: LOSS + METRICS + OPTIMIZER
# Dice only + manual metrics
# ============================================
dice_loss = smp.losses.DiceLoss(mode="binary", from_logits=True, smooth=1e-6)
bce_loss = nn.BCEWithLogitsLoss()

def combined_loss(logits, target):
    return 0.7 * dice_loss(logits, target) + 0.3 * bce_loss(logits, target)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=12, eta_min=1e-6)

scaler = torch.cuda.amp.GradScaler(enabled=(DEVICE == "cuda"))

def init_metric_sums():
    return {
        "tp": 0,
        "fp": 0,
        "fn": 0
    }

def update_metric_sums(metric_sums, pred, gt):
    pred = pred.bool()
    gt = gt.bool()

    metric_sums["tp"] += torch.logical_and(pred, gt).sum().item()
    metric_sums["fp"] += torch.logical_and(pred, ~gt).sum().item()
    metric_sums["fn"] += torch.logical_and(~pred, gt).sum().item()

def compute_metrics(metric_sums):
    tp = metric_sums["tp"]
    fp = metric_sums["fp"]
    fn = metric_sums["fn"]

    eps = 1e-7

    iou = tp / (tp + fp + fn + eps)
    precision = tp / (tp + fp + eps)
    recall = tp / (tp + fn + eps)
    f1 = (2 * tp) / (2 * tp + fp + fn + eps)

    return iou, f1, precision, recall

print("✅ Loss, optimizer, scheduler, metrics ready")
print("Loss: Dice only")
print("Metrics: manual IoU / F1 / Precision / Recall")

# ============================================
# CELL 12: TRAINING CONFIG
# ============================================
EPOCHS = 50
VAL_THRESH = 0.5
PATIENCE = 5
BEST_PATH = "/content/drive/MyDrive/unet_densenet169_scse_homodata.pth"

best_iou = 0.3977
best_epoch = 14
epochs_without_improve = 0

print("EPOCHS    :", EPOCHS)
print("VAL_THRESH:", VAL_THRESH)
print("PATIENCE  :", PATIENCE)
print("BEST_PATH :", BEST_PATH)

# ============================================
# CELL 13: TRAINING LOOP
# ============================================
for epoch in range(EPOCHS):
    model.train()
    train_loss_sum = 0.0
    epoch_start = time.time()

    for batch_idx, (img, mask) in enumerate(train_loader):
        img = img.to(DEVICE, non_blocking=True)
        mask = mask.to(DEVICE, non_blocking=True)

        if DEVICE == "cuda":
            img = img.contiguous(memory_format=torch.channels_last)

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast(device_type="cuda", enabled=(DEVICE == "cuda")):
            logits = model(img)
            loss = combined_loss(logits, mask)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        train_loss_sum += loss.item()

        if batch_idx % 100 == 0:
            print(
                f"Epoch {epoch+1}/{EPOCHS} | "
                f"Batch {batch_idx}/{len(train_loader)} | "
                f"Loss {loss.item():.4f}"
            )

    scheduler.step()

    # ---------------- VALIDATION ----------------
    model.eval()
    metric_sums = init_metric_sums()

    with torch.no_grad():
        for img, mask in val_loader:
            img = img.to(DEVICE, non_blocking=True)
            mask = mask.to(DEVICE, non_blocking=True)

            if DEVICE == "cuda":
                img = img.contiguous(memory_format=torch.channels_last)

            with torch.amp.autocast(device_type="cuda", enabled=(DEVICE == "cuda")):
                prob = torch.sigmoid(model(img))

            pred = (prob > VAL_THRESH).squeeze(1)
            gt   = (mask.squeeze(1) > 0.5)

            update_metric_sums(metric_sums, pred, gt)

    val_iou, val_f1, val_prec, val_rec = compute_metrics(metric_sums)
    avg_train_loss = train_loss_sum / len(train_loader)
    epoch_mins = (time.time() - epoch_start) / 60.0

    if val_iou > best_iou:
        best_iou = val_iou
        best_epoch = epoch + 1
        epochs_without_improve = 0
        torch.save({
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "scaler": scaler.state_dict(),
            "best_iou": best_iou,
            "best_epoch": best_epoch
        }, BEST_PATH)
        print("✅ Saved new best model to:", BEST_PATH)
    else:
        epochs_without_improve += 1

    print(
        f"Epoch {epoch+1}/{EPOCHS} | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Val IoU@{VAL_THRESH:.2f}: {val_iou:.4f} | "
        f"F1: {val_f1:.4f} | "
        f"P: {val_prec:.4f} | R: {val_rec:.4f} | "
        f"Best: {best_iou:.4f} (epoch {best_epoch}) | "
        f"Time: {epoch_mins:.2f} min"
    )

    if epochs_without_improve >= PATIENCE:
        print(f"⏹ Early stopping triggered after {PATIENCE} epochs without improvement.")
        break

print("\n✅ Training complete")
print("Best epoch:", best_epoch)
print("Best IoU  :", best_iou)
print("Saved to  :", BEST_PATH)

# ============================================
# CELL 14: FULL RESUME + SAFE TRAINING (FIXED)
# ============================================

import os
import torch
import time

RESUME = True
START_EPOCH = 19   # <-- YOU SET THIS (e.g., 11 if last completed epoch was 11)
USE_AMP = (DEVICE == "cuda")

# scaler
scaler = torch.amp.GradScaler("cuda", enabled=USE_AMP)

# ---------------- LOAD CHECKPOINT ----------------
if RESUME and os.path.exists(BEST_PATH):
    print("🔁 Loading checkpoint from:", BEST_PATH)

    checkpoint = torch.load(BEST_PATH, map_location=DEVICE)

    # -------- CASE 1: FULL CHECKPOINT --------
    if isinstance(checkpoint, dict) and "model" in checkpoint:
        model.load_state_dict(checkpoint["model"])

        if "optimizer" in checkpoint:
            optimizer.load_state_dict(checkpoint["optimizer"])
        if "scheduler" in checkpoint:
            scheduler.load_state_dict(checkpoint["scheduler"])
        if "scaler" in checkpoint and checkpoint["scaler"] is not None and USE_AMP:
            scaler.load_state_dict(checkpoint["scaler"])

        # ❗ IMPORTANT: DO NOT OVERRIDE START_EPOCH
        best_iou = checkpoint.get("best_iou", best_iou)
        best_epoch = checkpoint.get("best_epoch", best_epoch)

        print("✅ Loaded FULL checkpoint")
        print(f"🚀 Continuing from epoch {START_EPOCH}")
        print(f"🏆 Best IoU so far: {best_iou:.4f} (epoch {best_epoch})")

    # -------- CASE 2: WEIGHTS ONLY --------
    else:
        model.load_state_dict(checkpoint)

        optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=1e-4)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=12, eta_min=1e-6
        )
        scaler = torch.amp.GradScaler("cuda", enabled=USE_AMP)

        print("⚠️ Loaded weights-only checkpoint")
        print("➡️ Optimizer, scheduler, scaler reset")
        print(f"🚀 Starting from epoch {START_EPOCH}")

else:
    print("⚠️ No checkpoint found. Starting fresh.")

    START_EPOCH = 0
    optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=12, eta_min=1e-6
    )
    scaler = torch.amp.GradScaler("cuda", enabled=USE_AMP)


# ============================================
# TRAINING LOOP
# ============================================
for epoch in range(START_EPOCH, EPOCHS):
    model.train()
    train_loss_sum = 0.0
    epoch_start = time.time()

    for batch_idx, (img, mask) in enumerate(train_loader):
        img = img.to(DEVICE, non_blocking=True)
        mask = mask.to(DEVICE, non_blocking=True)

        if DEVICE == "cuda":
            img = img.contiguous(memory_format=torch.channels_last)

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast(device_type="cuda", enabled=USE_AMP):
            logits = model(img)
            loss = combined_loss(logits, mask)

        if USE_AMP:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()

        train_loss_sum += loss.item()

        if batch_idx % 100 == 0:
            print(
                f"Epoch {epoch+1}/{EPOCHS} | "
                f"Batch {batch_idx}/{len(train_loader)} | "
                f"Loss {loss.item():.4f}"
            )

    scheduler.step()

    # ---------------- VALIDATION ----------------
    model.eval()
    metric_sums = init_metric_sums()

    with torch.no_grad():
        for img, mask in val_loader:
            img = img.to(DEVICE, non_blocking=True)
            mask = mask.to(DEVICE, non_blocking=True)

            if DEVICE == "cuda":
                img = img.contiguous(memory_format=torch.channels_last)

            with torch.amp.autocast(device_type="cuda", enabled=USE_AMP):
                prob = torch.sigmoid(model(img))

            pred = (prob > VAL_THRESH).squeeze(1)
            gt = (mask.squeeze(1) > 0.5)

            update_metric_sums(metric_sums, pred, gt)

    val_iou, val_f1, val_prec, val_rec = compute_metrics(metric_sums)
    avg_train_loss = train_loss_sum / len(train_loader)
    epoch_mins = (time.time() - epoch_start) / 60.0

    # ---------------- SAVE BEST ----------------
    if val_iou > best_iou:
        best_iou = val_iou
        best_epoch = epoch + 1
        epochs_without_improve = 0

        torch.save({
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "scaler": scaler.state_dict() if USE_AMP else None,
            "best_iou": best_iou,
            "best_epoch": best_epoch
        }, BEST_PATH)

        print("✅ New BEST checkpoint saved")

    else:
        epochs_without_improve += 1

    print(
        f"Epoch {epoch+1}/{EPOCHS} | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Val IoU@{VAL_THRESH:.2f}: {val_iou:.4f} | "
        f"F1: {val_f1:.4f} | "
        f"P: {val_prec:.4f} | "
        f"R: {val_rec:.4f} | "
        f"Best: {best_iou:.4f} (epoch {best_epoch}) | "
        f"Time: {epoch_mins:.2f} min"
    )

    if epochs_without_improve >= PATIENCE:
        print(f"⏹ Early stopping triggered after {PATIENCE} epochs without improvement.")
        break


print("\n✅ Training complete")
print("🏆 Best epoch:", best_epoch)
print("🏆 Best IoU :", best_iou)
print("💾 Saved to :", BEST_PATH)

# ============================================
# CELL: FINAL TRAIN METRICS
# ============================================

MANUAL_THRESH = 0.80

checkpoint = torch.load(BEST_PATH, map_location=DEVICE)

if isinstance(checkpoint, dict) and "model" in checkpoint:
    model.load_state_dict(checkpoint["model"])
else:
    model.load_state_dict(checkpoint)

model.to(DEVICE).eval()

metric_sums = init_metric_sums()

USE_AMP = (DEVICE == "cuda")
eval_thresh = MANUAL_THRESH

with torch.inference_mode():
    for img, mask in train_loader:   # ✅ CHANGED HERE
        img = img.to(DEVICE, non_blocking=True)
        mask = mask.to(DEVICE, non_blocking=True)

        if DEVICE == "cuda":
            img = img.contiguous(memory_format=torch.channels_last)

        with torch.amp.autocast(device_type="cuda", enabled=USE_AMP):
            prob = torch.sigmoid(model(img))

        pred = (prob > eval_thresh).squeeze(1)
        gt = (mask.squeeze(1) > 0.5)

        update_metric_sums(metric_sums, pred, gt)

if DEVICE == "cuda":
    torch.cuda.synchronize()

final_iou, final_f1, final_prec, final_rec = compute_metrics(metric_sums)

print("📌 FINAL TRAIN RESULTS")
print("Checkpoint :", BEST_PATH)
print("Threshold  :", eval_thresh)
print("IoU        : {:.2f}%".format(final_iou * 100))
print("F1         : {:.2f}%".format(final_f1 * 100))
print("Precision  : {:.2f}%".format(final_prec * 100))
print("Recall     : {:.2f}%".format(final_rec * 100))

if isinstance(checkpoint, dict):
    print("Best epoch  :", checkpoint.get("best_epoch", "N/A"))
    print("Best IoU    :", checkpoint.get("best_iou", "N/A"))

# ============================================
# CELL 16: VISUALIZE ONE VAL SAMPLE
# ============================================

def tensor_to_display_rgb(img_chw):
    x = img_chw.detach().cpu().numpy()
    x = np.transpose(x, (1, 2, 0))
    x = x[:, :, :3]

    out = np.zeros_like(x, dtype=np.float32)
    for c in range(x.shape[-1]):
        ch = x[:, :, c]
        mn, mx = ch.min(), ch.max()
        if mx - mn < 1e-6:
            out[:, :, c] = 0.0
        else:
            out[:, :, c] = (ch - mn) / (mx - mn)
    return np.clip(out, 0, 1)


IMG_NAME = val_images[550]   # change manually if needed
THRESH = 0.50

img_path = os.path.join(VAL_IMG, IMG_NAME)
mask_path = os.path.join(VAL_MSK, expected_mask_name_from_image(IMG_NAME))

print("IMG :", img_path)
print("MASK:", mask_path)

with rasterio.open(img_path) as src:
    raw_img = src.read().transpose(1, 2, 0).astype(np.float32)

with rasterio.open(mask_path) as src:
    raw_mask = src.read(1).astype(np.float32)

gt = (raw_mask > 0).astype(np.uint8)

# ---- FEATURE EXTRACTION ----
proc_img, used_indices = compute_input_features(raw_img)

# ---- APPLY SAME NORMALIZATION AS TRAINING ----
proc_img = (proc_img - DATA_MEAN) / DATA_STD

# ---- TO TENSOR ----
img_t = torch.from_numpy(proc_img).permute(2, 0, 1).unsqueeze(0).float().to(DEVICE)

if DEVICE == "cuda":
    img_t = img_t.contiguous(memory_format=torch.channels_last)

# ---- LOAD MODEL SAFELY ----
checkpoint = torch.load(BEST_PATH, map_location=DEVICE)

if isinstance(checkpoint, dict) and "model" in checkpoint:
    model.load_state_dict(checkpoint["model"])
else:
    model.load_state_dict(checkpoint)

model.to(DEVICE).eval()

# ---- INFERENCE ----
USE_AMP = (DEVICE == "cuda")

with torch.inference_mode():
    with torch.amp.autocast(device_type="cuda", enabled=USE_AMP):
        prob = torch.sigmoid(model(img_t))

pred = (prob > THRESH).squeeze().detach().cpu().numpy().astype(np.uint8)
prob_map = prob.squeeze().detach().cpu().numpy()

img_show = tensor_to_display_rgb(img_t[0])

# ---- DEBUG PRINTS ----
print("Checkpoint used:", BEST_PATH)
print("Used NDVI/NDWI :", used_indices)
print("GT pixels      :", int(gt.sum()))
print("Pred pixels    :", int(pred.sum()))
print("Pred/GT ratio  :", float(pred.sum() / max(gt.sum(), 1)))
print("Prob min/max   :", float(prob.min()), float(prob.max()))
print("Prob mean      :", float(prob.mean()))

if isinstance(checkpoint, dict):
    print("Best epoch     :", checkpoint.get("best_epoch", "N/A"))
    print("Best IoU       :", checkpoint.get("best_iou", "N/A"))

# ---- PLOTS ----
plt.figure(figsize=(20, 5))

plt.subplot(1, 4, 1)
plt.title("Input")
plt.imshow(img_show)
plt.axis("off")

plt.subplot(1, 4, 2)
plt.title("GT mask")
plt.imshow(gt, cmap="gray")
plt.axis("off")

plt.subplot(1, 4, 3)
plt.title(f"Pred @ {THRESH:.2f}")
plt.imshow(pred, cmap="gray")
plt.axis("off")

plt.subplot(1, 4, 4)
plt.title("Heatmap overlay")
plt.imshow(img_show)
plt.imshow(prob_map, cmap="jet", alpha=0.40, vmin=0, vmax=1)
plt.axis("off")

plt.tight_layout()
plt.show()

